/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Home
 */
public class Frm_Escuela extends javax.swing.JDialog {

    /**
     * Creates new form Frm_Escuela
     */
    public Frm_Escuela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtlongitud = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtubicacion = new javax.swing.JTextField();
        txtlatitud = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableescuelas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxdestino = new javax.swing.JComboBox<>();
        cbxorigen = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel2.setLayout(null);

        jLabel1.setText("UBICACION");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 80, 80, 16);

        jLabel2.setText("LONGITUD");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 80, 80, 16);

        jLabel3.setText("NOMBRE:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 30, 80, 16);

        jLabel4.setText("LATITUD");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(280, 30, 80, 16);
        jPanel2.add(txtlongitud);
        txtlongitud.setBounds(350, 70, 130, 30);
        jPanel2.add(txtnombre);
        txtnombre.setBounds(90, 24, 130, 30);
        jPanel2.add(txtubicacion);
        txtubicacion.setBounds(90, 74, 130, 30);
        jPanel2.add(txtlatitud);
        txtlatitud.setBounds(350, 20, 130, 30);

        jButton1.setText("Guradar");
        jPanel2.add(jButton1);
        jButton1.setBounds(520, 70, 80, 24);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 620, 140);

        jPanel3.setLayout(null);

        tableescuelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableescuelas);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 59, 440, 170);

        jLabel5.setText("Destino");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(190, 10, 41, 16);

        jLabel6.setText("Origen");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 10, 37, 16);

        jPanel3.add(cbxdestino);
        cbxdestino.setBounds(240, 10, 100, 26);

        jPanel3.add(cbxorigen);
        cbxorigen.setBounds(70, 10, 100, 26);

        jButton2.setText("Agregar");
        jPanel3.add(jButton2);
        jButton2.setBounds(380, 10, 70, 24);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 160, 620, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Escuela dialog = new Frm_Escuela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxdestino;
    private javax.swing.JComboBox<String> cbxorigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableescuelas;
    private javax.swing.JTextField txtlatitud;
    private javax.swing.JTextField txtlongitud;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtubicacion;
    // End of variables declaration//GEN-END:variables
}
